//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofka_Prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public int id { get; set; }
        public string texto { get; set; }
        public short points { get; set; }
        public int question_id { get; set; }
    
        public virtual question question { get; set; }
    }
}
